[colors]
background                      = "35362E"
dim-foreground                  = "E5E3EE"
foreground                      = "DCD9E4"
light-foreground                = "C8C5D0"

black                           = "DCD9E4"
red                             = "FECCCF"
green                           = "B0EAD2"
yellow                          = "EADBA3"
blue                            = "CBDBFA"
magenta                         = "EAD1ED"
cyan                            = "B0E5F0"
white                           = "35362E"

dim-black                       = "E5E3EE"
dim-red                         = "EFB6BC"
dim-green                       = "94D8BF"
dim-yellow                      = "D9C788"
dim-blue                        = "B5C8ED"
dim-magenta                     = "D9BCDE"
dim-cyan                        = "95D3E1"
dim-white                       = "4A4B42"

light-black                     = "C8C5D0"
light-red                       = "5A3336"
light-green                     = "0F4B39"
light-yellow                    = "4C3F03"
light-blue                      = "334059"
light-magenta                   = "4B374E"
light-cyan                      = "124850"
light-white                     = "2B2C24"

cursor                          = "D2CFDA"
vi-cursor                       = "94D8BF"

tabs                            = "D2CFDA"
tabs-active                     = "D2CFDA"
tabs-active-highlight           = "D2CFDA"
tabs-active-foreground          = "2B2C24"
tabs-foreground                 = "DCD9E4"
bar                             = "403E47"

search-match-background         = "334059"
search-match-foreground         = "DCD9E4"
search-focused-match-background = "D9BCDE"
search-focused-match-foreground = "2B2C24"

selection-background            = "4A4B42"
selection-foreground            = "DCD9E4"
