[colors]
background                      = "E8E9DE"
dim-foreground                  = "39363F"
foreground                      = "403E47"
light-foreground                = "504E57"

black                           = "403E47"
red                             = "5A3336"
green                           = "0F4B39"
yellow                          = "4C3F03"
blue                            = "334059"
magenta                         = "4B374E"
cyan                            = "124850"
white                           = "E8E9DE"

dim-black                       = "39363F"
dim-red                         = "6F4046"
dim-green                       = "155D49"
dim-yellow                      = "5F4E09"
dim-blue                        = "404F6F"
dim-magenta                     = "5E4663"
dim-cyan                        = "185965"
dim-white                       = "CECFC4"

light-black                     = "504E57"
light-red                       = "FECCCF"
light-green                     = "B0EAD2"
light-yellow                    = "EADBA3"
light-blue                      = "CBDBFA"
light-magenta                   = "EAD1ED"
light-cyan                      = "B0E5F0"
light-white                     = "F5F6EB"

cursor                          = "48464F"
vi-cursor                       = "155D49"

tabs                            = "48464F"
tabs-active                     = "48464F"
tabs-active-highlight           = "48464F"
tabs-active-foreground          = "F5F6EB"
tabs-foreground                 = "403E47"
bar                             = "DCD9E4"

search-match-background         = "CBDBFA"
search-match-foreground         = "403E47"
search-focused-match-background = "5E4663"
search-focused-match-foreground = "F5F6EB"

selection-background            = "CECFC4"
selection-foreground            = "403E47"
