---@class Scheme
---@field d0_black      string
---@field d0_white      string
---@field d1_black      string
---@field d1_white      string
---@field d2_black      string
---@field d2_white      string
---@field d3_black      string
---@field d3_white      string
---@field d1_red        string
---@field d1_orange     string
---@field d1_yellow     string
---@field d1_chartreuse string
---@field d1_green      string
---@field d1_cyan       string
---@field d1_blue       string
---@field d1_purple     string
---@field d3_red        string
---@field d3_orange     string
---@field d3_yellow     string
---@field d3_chartreuse string
---@field d3_green      string
---@field d3_cyan       string
---@field d3_blue       string
---@field d3_purple     string
---@field v0_black      string
---@field v0_white      string
---@field v1_black      string
---@field v1_white      string
---@field v2_black      string
---@field v2_white      string
---@field v3_black      string
---@field v3_white      string
---@field v2_red        string
---@field v2_orange     string
---@field v2_yellow     string
---@field v2_chartreuse string
---@field v2_green      string
---@field v2_cyan       string
---@field v2_blue       string
---@field v2_purple     string

---@class Palette

---@class Config
---@field colors	Scheme
---@field options?  Options
---@field overides? HighlightGroups
---@field theme		string

---@class Options
---@field clear?         OptionTable
---@field bold?          OptionTable
---@field strikethrough? OptionTable
---@field underline?     OptionTable
---@field undercurl?     OptionTable
---@field underdouble?   OptionTable
---@field underdotted?   OptionTable
---@field underdashed?   OptionTable
---@field italic?        OptionTable

---@class UserConfig
---@field options?  Options
---@field overides? HighlightGroups
---@field theme?	string

---@alias OptionTable table<string,boolean>
---@alias HighlightGroups table<string,vim.api.keyset.highlight>
---@alias Color table<vim.api.keyset.highlight> | string
