---@class Scheme
---@field d0_black      string
---@field d0_white      string
---@field d1_black      string
---@field d1_white      string
---@field d2_black      string
---@field d2_white      string
---@field d3_black      string
---@field d3_white      string
---@field d1_red        string
---@field d1_orange     string
---@field d1_yellow     string
---@field d1_chartreuse string
---@field d1_green      string
---@field d1_cyan       string
---@field d1_blue       string
---@field d1_purple     string
---@field d3_red        string
---@field d3_orange     string
---@field d3_yellow     string
---@field d3_chartreuse string
---@field d3_green      string
---@field d3_cyan       string
---@field d3_blue       string
---@field d3_purple     string
---@field v0_black      string
---@field v0_white      string
---@field v1_black      string
---@field v1_white      string
---@field v2_black      string
---@field v2_white      string
---@field v3_black      string
---@field v3_white      string
---@field v2_red        string
---@field v2_orange     string
---@field v2_yellow     string
---@field v2_chartreuse string
---@field v2_green      string
---@field v2_cyan       string
---@field v2_blue       string
---@field v2_purple     string

---@class Config
---@field colors	Scheme
---@field options   Options
---@field overides? HighlightGroups
---@field theme		string

---@class UserConfig
---@field options?  Options
---@field overides? HighlightGroups
---@field theme?	string

---@alias HighlightGroups table<string,vim.api.keyset.highlight> -- ["@string"] = { fg = "#222222", italic = true },

---@class Options
---@field sideBarDim?	   boolean -- if false then sidebar bg is same normal, default is true
---@field statusBarRevers? boolean -- if false then statusBarRevers bg is d2_black, default is true
---@field NCWindowDim?     boolean -- if false then not current window bg is same normal, default is true
---@field str?			   string -- none, bold or italic, default is none
---@field statement?       string -- none, bold or italic, default is none
---@field func?			   string -- none, bold or italic, default is none
---@field type?			   string -- none, bold or italic, default is none
---@field constant?        string -- none, bold or italic, default is none
---@field keyword?         string -- none, bold or italic, default is none
