---@class Scheme
---@field d0_black      string
---@field d0_white      string
---@field d1_black      string
---@field d1_white      string
---@field d2_black      string
---@field d2_white      string
---@field d3_black      string
---@field d3_white      string
---@field d1_red        string
---@field d1_orange     string
---@field d1_yellow     string
---@field d1_chartreuse string
---@field d1_green      string
---@field d1_cyan       string
---@field d1_blue       string
---@field d1_purple     string
---@field d3_red        string
---@field d3_orange     string
---@field d3_yellow     string
---@field d3_chartreuse string
---@field d3_green      string
---@field d3_cyan       string
---@field d3_blue       string
---@field d3_purple     string
---@field v0_black      string
---@field v0_white      string
---@field v1_black      string
---@field v1_white      string
---@field v2_black      string
---@field v2_white      string
---@field v3_black      string
---@field v3_white      string
---@field v2_red        string
---@field v2_orange     string
---@field v2_yellow     string
---@field v2_chartreuse string
---@field v2_green      string
---@field v2_cyan       string
---@field v2_blue       string
---@field v2_purple     string

---@class Palette
---@field tc TerminalColor
---@field di Diagnostic
---@field fg Foreground
---@field bg Background
---@field sy Syntax
---@field df Diff
---@field rb Rainbow
---@field at Attr
---@field ui UI

---@class TerminalColor
---@field black             Color
---@field red               Color
---@field orange            Color
---@field yellow            Color
---@field chartreuse        Color
---@field green             Color
---@field cyan              Color
---@field blue              Color
---@field purple            Color
---@field white             Color
---@field bright_black      Color
---@field bright_red        Color
---@field bright_orange     Color
---@field bright_yellow     Color
---@field bright_chartreuse Color
---@field bright_green      Color
---@field bright_cyan       Color
---@field bright_blue       Color
---@field bright_purple     Color
---@field bright_white      Color

---@class Diagnostic
---@field error         Color
---@field warn          Color
---@field ok            Color
---@field info          Color
---@field hint          Color

---@class Rainbow
---@field rb1           Color
---@field rb2           Color
---@field rb3           Color
---@field rb4           Color
---@field rb5           Color
---@field rb6           Color
---@field rb7           Color

---@class Diff
---@field delete        Color
---@field add           Color
---@field change        Color
---@field difftext      Color

---@class Attr
---@field clear         Color
---@field bold          Color
---@field strikethrough Color
---@field underline     Color
---@field undercurl     Color
---@field underdouble   Color
---@field underdotted   Color
---@field underdashed   Color
---@field italic        Color

---@class Foreground
---@field strong        Color
---@field text          Color
---@field comment       Color

---@class Background
---@field float         Color
---@field plain			Color
---@field visual        Color

---@class UI
---@field error		 Color
---@field warn	     Color
---@field ok		 Color
---@field info       Color
---@field hint       Color
---@field select     Color
---@field candidate  Color
---@field match		 Color
---@field line		 Line
---@field cursor     Color
---@field fold       Color
---@field subtitute  Color
---@field nontext    Color
---@field special	 Color
---@field title      Color
---@field sign       Color
---@field pmenu      Color
---@field pselect    Color
---@field nc	     Color

---@class Line
---@field active     Color
---@field inactive   Color
---@field light      Color
---@field dark       Color
---@field cursor	 Color
---@field side		 Color
---@field border     Color

---@class Syntax
---@field error		 Color
---@field warn		 Color
---@field todo		 Color
---@field note		 Color
---@field keyword    Color
---@field constant   Color
---@field type       Color
---@field macro      Color
---@field functions  Color
---@field statement  Color
---@field modifier   Color
---@field operator   Color
---@field string     Color
---@field symbol	 Color
---@field struct     Color
---@field member     Color
---@field parameter  Color
---@field variable   Color
---@field construct  Color
---@field special    Color

---@class Config
---@field colors	Scheme
---@field options?  Options
---@field overides? HighlightGroups
---@field theme		string

---@class Options
---@field clear?         OptionTable
---@field bold?          OptionTable
---@field strikethrough? OptionTable
---@field underline?     OptionTable
---@field undercurl?     OptionTable
---@field underdouble?   OptionTable
---@field underdotted?   OptionTable
---@field underdashed?   OptionTable
---@field italic?        OptionTable

---@class UserConfig
---@field options?  Options
---@field overides? HighlightGroups
---@field theme?	string

---@alias OptionTable table<string,boolean>
---@alias HighlightGroups table<string,vim.api.keyset.highlight>
---@alias Color table<vim.api.keyset.highlight> | string
