---@return Palette
return {
	d0_black   = "$(d0_black)",
	d0_white   = "$(d0_white)",
	d1_black   = "$(d1_black)",
	d1_white   = "$(d1_white)",
	d2_black   = "$(d2_black)",
	d2_white   = "$(d2_white)",
	d3_black   = "$(d3_black)",
	d3_white   = "$(d3_white)",
	d3_red     = "$(d3_red)",
	d3_orange  = "$(d3_orange)",
	d3_yellow  = "$(d3_yellow)",
	d3_green   = "$(d3_green)",
	d3_mint    = "$(d3_mint)",
	d3_cyan    = "$(d3_cyan)",
	d3_blue    = "$(d3_blue)",
	d3_magenta = "$(d3_magenta)",
	v0_black   = "$(v0_black)",
	v0_white   = "$(v0_white)",
	v1_black   = "$(v1_black)",
	v1_white   = "$(v1_white)",
	v2_black   = "$(v2_black)",
	v2_white   = "$(v2_white)",
	v3_black   = "$(v3_black)",
	v3_white   = "$(v3_white)",
	v3_red     = "$(v3_red)",
	v3_orange  = "$(v3_orange)",
	v3_yellow  = "$(v3_yellow)",
	v3_green   = "$(v3_green)",
	v3_mint    = "$(v3_mint)",
	v3_cyan    = "$(v3_cyan)",
	v3_blue    = "$(v3_blue)",
	v3_magenta = "$(v3_magenta)",
}
