palette = 0=#4B4248
palette = 1=#70384E
palette = 2=#235751
palette = 3=#614820
palette = 4=#454876
palette = 5=$(d3_magenta)
palette = 6=#26526C
palette = 7=#CDD7D0
palette = 8=#534A50
palette = 9=#70384E
palette = 10=#235751
palette = 11=#614820
palette = 12=#454876
palette = 13=$(d3_magenta)
palette = 14=#26526C
palette = 15=#E7F2EA

background =#DAE4DD
foreground =#433A40
cursor-color =#534A50
selection-background =#CEC4CB
selection-foreground =#37403A 
