palette = 0=#D4D6C7
palette = 1=#F5BBCC
palette = 2=#9BDDCF
palette = 3=#DFCC99
palette = 4=#BCCCFD
palette = 5=$(d3_magenta)
palette = 6=#9CD8F0
palette = 7=#403C51
palette = 8=#CECFC1
palette = 9=#F5BBCC
palette = 10=#9BDDCF
palette = 11=#DFCC99
palette = 12=#BCCCFD
palette = 13=$(d3_magenta)
palette = 14=#9CD8F0
palette = 15=#2B2A35

background =#363246
foreground =#DBDCCE
cursor-color =#CECFC1
selection-background =#53553E
selection-foreground =#DBD9E7 
