palette = 0=#403F45
palette = 1=#633443
palette = 2=#025146
palette = 3=#544310
palette = 4=#36436B
palette = 5=$(d3_magenta)
palette = 6=#094C61
palette = 7=#D4D5CE
palette = 8=#45444A
palette = 9=#633443
palette = 10=#025146
palette = 11=#544310
palette = 12=#36436B
palette = 13=$(d3_magenta)
palette = 14=#094C61
palette = 15=#EEEFE8

background =#E1E2DB
foreground =#3A3A3F
cursor-color =#45444A
selection-background =#BEBDC4
selection-foreground =#3A3B35 
