palette = 0=#C7C8BE
palette = 1=#E7AABC
palette = 2=#86CEBF
palette = 3=#D0BC86
palette = 4=#ABBCEF
palette = 5=$(d3_magenta)
palette = 6=#88C9E2
palette = 7=#363246
palette = 8=#BDBFB4
palette = 9=#E7AABC
palette = 10=#86CEBF
palette = 11=#D0BC86
palette = 12=#ABBCEF
palette = 13=$(d3_magenta)
palette = 14=#88C9E2
palette = 15=#222028

background =#2C283B
foreground =#D1D2C7
cursor-color =#BDBFB4
selection-background =#40422C
selection-foreground =#D1CFDA 
